"""user table

Revision ID: 505836dfbe2e
Revises: 
Create Date: 2020-06-12 17:26:44.238564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505836dfbe2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ssnid', sa.Integer(), nullable=True),
    sa.Column('uname', sa.String(length=50), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('addr1', sa.Text(), nullable=True),
    sa.Column('addr2', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('is_cust', sa.Integer(), nullable=True),
    sa.Column('created', sa.Date(), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_ssnid'), 'user', ['ssnid'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ssnid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
