"""empty message

Revision ID: b8b908a727ef
Revises: 595c70886d1d
Create Date: 2020-06-15 12:35:38.046496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b908a727ef'
down_revision = '595c70886d1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('tr_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'tr_type')
    # ### end Alembic commands ###
