"""empty message

Revision ID: e79fdfc8c943
Revises: 
Create Date: 2020-06-14 13:46:21.365424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e79fdfc8c943'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('cust_id', sa.Integer(), nullable=False),
    sa.Column('cust_ssn', sa.Integer(), nullable=True),
    sa.Column('cust_name', sa.String(length=20), nullable=True),
    sa.Column('cust_age', sa.Integer(), nullable=True),
    sa.Column('cust_addr1', sa.Text(), nullable=True),
    sa.Column('cust_addr2', sa.Text(), nullable=True),
    sa.Column('cust_city', sa.String(length=20), nullable=True),
    sa.Column('cust_state', sa.String(length=20), nullable=True),
    sa.Column('cust_last_update', sa.Date(), nullable=True),
    sa.Column('cust_status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('cust_id')
    )
    op.create_index(op.f('ix_customer_cust_ssn'), 'customer', ['cust_ssn'], unique=True)
    op.create_table('login',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uname', sa.String(length=20), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uname')
    )
    op.create_table('transaction',
    sa.Column('tr_id', sa.Integer(), nullable=False),
    sa.Column('tr_amount', sa.Integer(), nullable=True),
    sa.Column('tr_date', sa.DateTime(), nullable=True),
    sa.Column('tr_src', sa.Integer(), nullable=True),
    sa.Column('tr_trgt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tr_id')
    )
    op.create_table('account',
    sa.Column('acnt_id', sa.Integer(), nullable=False),
    sa.Column('cust_id', sa.Integer(), nullable=True),
    sa.Column('acnt_type', sa.String(length=20), nullable=True),
    sa.Column('acnt_balance', sa.Integer(), nullable=True),
    sa.Column('acnt_last_tr_date', sa.DateTime(), nullable=True),
    sa.Column('acnt_status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cust_id'], ['customer.cust_id'], ),
    sa.PrimaryKeyConstraint('acnt_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.drop_table('transaction')
    op.drop_table('login')
    op.drop_index(op.f('ix_customer_cust_ssn'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
